version: '3.3'
services:
  postgres:
    image: 063846433154.dkr.ecr.eu-central-1.amazonaws.com/sggw:latest
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5555:443'
