version: '3.7'
services:
  postgres:
    image: postgres:16.1
    container_name: database-specjalisci
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=!qqG9zfE^Ze!4k
      - PGDATA=/data/postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql