export const FILTERS_NAME_MAPPING = new Map<string, string>([
  ["office", "Stacjonarne"],
  ["remote", "Mobilne"],

  ["tiles", "Budowa Domu"],
  ["painting", "Malowanie Ścian"],
  ["bath", "Montaż mebli"],
  ["hydraulics", "Naprawa Elektryki"],

  ["printer", "Programowanie Mikrokontrolerów"],
  ["laptop", "Inżynieria Oprogramowania"],
  ["phone", "Sztuczna Inteligencja"],
  ["network", "Bezpieczeństwo Sieciowie"],
  ["integration", "Intergracja Systemów"],
  ["desktop", "Rozwój Aplikacji Desktopwych"],
  ["mobile", "Tworzenie Aplikacji Mobilnych"],
  ["cloud", "Cloud Computing"],
  ["cybersec", "Cybersecurity"],
  ["testing", "Testowanie Oprogramowania"],
  ["www", "Optymalizacja Stron WWW"],
  ["server", "Administracja Serwerami"],
  ["website", "Tworzenie Stron Internetowych"],
  ["data", "Analiza Danych"],
  ["graphic", "Projektowanie Graficzne Stron"],

  ["sprzatanie", "Usługi Sprzątające"],
  ["elektronika", "Naprawa Elektroniki"],
  ["opieka", "Opieka Dziecięca"],
  ["finanse", "Doradztwo Finansowe"],
]);
