# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Frontend CI

on:
  push:
    branches: [ "master" ]
    paths:
    - 'helpHunter-ui/**' 
  pull_request:
    branches: [ "master" ]
    paths:
    - 'helpHunter-ui/**' 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        path: 'specjalisci/helpHunter-ui/'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npx ng build --configuration production --output-path /app/testy
    - run: npm test
